[project]
name = "mhpss-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.25",
    "langchain-chroma>=0.2.4",
    "langchain-ollama>=0.3.3",
    "langgraph>=0.4.8",
    "mistralai>=1.8.2",
]
